name: Swift
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macOS-latest
    name: Unit-Tests Package ${{ matrix.package }} on Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: ["12.4", "13.2.1"]
        package: ["Cachable", "CombineExtension", "CombineUIKit"," Core", "Identifier", "LinkedListDataStructure", "PropertyWrapper", "SwiftExtension", "UIExtension"]
    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode
      run: |
        echo "Available Xcode versions:"
        ls /Applications | grep Xcode
        echo "Choosing Xcode_${{ matrix.xcode }}.app"
        sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
        xcodebuild -version
        swift --version
        swift package --version
    - name: Build & Test Cachable
      run: |
        xcodebuild -scheme ${{ matrix.package }} test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
    

        
        